SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW
FROM "MEMBER";

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NICKNAME
		,TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') AS ENROLL_DATE
		FROM "MEMBER"
		WHERE MEMBER_DEL_FL = 'N'
		AND MEMBER_ID = ?
		AND MEMBER_PW = ?;

	
	
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER"(
	MEMBER_ID VARCHAR2(20)PRIMARY KEY, -- 아이디
	MEMBER_PW VARCHAR2(20) NOT NULL, -- 비번
	MEMBER_NICKNAME VARCHAR2(20) NOT NULL, -- 이름
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 생성일
	MEMBER_DEL_FL	CHAR(1)	DEFAULT 'N'	NOT NULL -- 탈퇴여부
);
	
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NICKNAME IS '회원 이름';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '생성일';
COMMENT ON COLUMN "MEMBER".MEMBER_DEL_FL IS '탈퇴여부';


INSERT INTO "MEMBER" VALUES
('user01', 'pass01', '유저일', DEFAULT, 'N');
INSERT INTO "MEMBER" VALUES
('user02', 'pass02', '유저이', DEFAULT, 'N');


	
----------------------------------------------------------	
CREATE TABLE BOARD(
	BOARD_NO NUMBER PRIMARY KEY, -- 게시글 번호
	BOARD_TITLE VARCHAR2(50), -- 게시글 제목
	BOARD_CONTENT VARCHAR2(500), -- 게시글 내용
	BOARD_HIT NUMBER, -- 조회수
	MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_ID_FK REFERENCES "MEMBER"
	
);


DROP TABLE BOARD;


COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.BOARD_HIT IS '게시글 조회수';
COMMENT ON COLUMN BOARD.MEMBER_ID IS '회원 아이디';


INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '게시글1', '1번 게시글 내용', 2, 'user01');
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '게시글2', '2번 게시글 내용', 1, 'user02');


----------------- 시퀀스 --------------------
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_HIT FROM BOARD;


CREATE TABLE "COMMENT"(
	COMMENT_NO NUMBER PRIMARY KEY, -- 댓글 번호
	COMMENT_CONTENT VARVHAR2(500), -- 댓글 내용
	MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_ID_FK REFERENCES "MEMBER" -- 댓글단사람
	
	
);

SELECT * FROM COMUNITY;



SELECT MEMBER_ID, MEMBER_NICKNAME
		,TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') AS ENROLL_DATE
		FROM "MEMBER"
		WHERE MEMBER_DEL_FL = 'N'
		AND MEMBER_ID = 'user01'
		AND MEMBER_PW = 'pass01';

CREATE TABLE 
	
	
	
COMMIT;
