CREATE TABLE "MEMBER" (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) UNIQUE,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(20),
	ENROLL_DATE DATE DEFAULT SYSDATE,
	MEMBER_DEL_FL CHAR(1)
	
);


COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NICKNAME IS '회원 이름';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입 날짜';
COMMENT ON COLUMN "MEMBER".MEMBER_DEL_FL IS '탈퇴 여부';


CREATE SEQUENCE SEQ_TEMP
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO "MEMBER" VALUES(1, 'user01', 'pass01', '유저일', DEFAULT, 'N');
INSERT INTO "MEMBER" VALUES(2, 'user02', 'pass02', '유저이', DEFAULT, 'N');
INSERT INTO "MEMBER" VALUES(3, 'user03', 'pass03', '유저삼', DEFAULT, 'N');

SELECT * FROM "MEMBER";

COMMIT;